### PR TITLE
[PR] Add support for async controller functions

### PR DESCRIPTION
**Pull request by JLaferri**
I added an example to server.js. This allows for the controller functions to be defined as async.

I had to `--no-verify` my commit because I was encountering the following error and wasn't quite sure how to get past it.
image

Also I used yarn which generated a yarn.lock file, hopefully this is okay.

### CODE REVIEW

**Comment by nishant-labs** [comment]
@JLaferri Thanks for the PR.

I am curious to understand the scenario where you need async in the controller. Also, I would really appreciate if you could raise an issue explaining the change and usage so that I can make some optimisation in code if needed.

**Comment by JLaferri** [comment]
Created issue: https://github.com/nishant-labs/node-rest-server/issues/31

Would you like me to just add the lib folder and the lock file to gitignore or would you prefer a different method of removal? I was under the impression that committing the lock files is a best practice but I also have been annoyed by it in the past lol.

**Comment by nishant-labs** [comment]
@JLaferri You can just remove those 2 files for now, I will add lib while releasing a new version.

I was a bit away from this repo for a long time.

**Comment by JLaferri** [comment]
Those changes are no longer included

**Pull request merged**
